server:
  port: 8089

spring:
  datasource:
    driver-class-name: ${DB_DRIVER:org.postgresql.Driver}
    host: ${DB_HOST:localhost}
    port: ${DB_PORT:5432}
    name: ${POSTGRES_DB:postgres}
    url: jdbc:postgresql://${spring.datasource.host}:${spring.datasource.port}/${spring.datasource.name}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:assoul}

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      show-sql: 'true'
      ddl-auto: update